declare a as integer

try
	a="XXXXXXXXXXXXXXXXX"
catch
	print "Caught error"
endtry



